services:
  - type: web
    plan: free
    name: Zaid
    env: docker
    #buildCommand: pip install -U -r requirements.txt
    #startCommand: gunicorn app:app & python3 -m Zaid
    repo: https://github.com/assc0d3r/tgfwdauto      
    branch: main
    envVars:
      - key: SESSION 
        sync: false
      - key: TO_CHANNEL 
        sync: false
      - key: FROM_CHANNEL 
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false    
    autoDeploy: false
